const sentences = [
    "The sun is shining.",
    "She walked to the store.",
    "He likes to play guitar.",
    "They are going on vacation.",
    "The cat is sleeping.",
    "I enjoy reading books.",
    "We went for a hike.",
    "She cooked dinner for her family.",
    "He is learning a new language.",
    "The flowers are blooming.",
    "The children are playing in the park.",
    "She is studying for her exams.",
    "He fixed the broken window.",
    "They visited the museum last weekend.",
    "The dog chased its tail.",
    "I love listening to music.",
    "We had pizza for dinner.",
    "She wrote a letter to her friend.",
    "He rode his bike to school.",
    "The movie starts at 7 PM.",
    "They went fishing by the lake.",
    "She danced at the party.",
    "He cleaned his room yesterday.",
    "We watched the sunrise together.",
    "The birds are singing outside.",
    "I enjoy taking long walks.",
    "She baked cookies for the charity sale.",
    "He played basketball with his friends.",
    "The teacher explained the lesson clearly.",
    "They planted trees in the garden.",
    "The clock is ticking.",
    "She watered the plants in the garden.",
    "He read a fascinating book last night.",
    "They organized a picnic by the river.",
    "The baby laughed uncontrollably.",
    "I cooked breakfast this morning.",
    "We visited our grandparents on Sunday.",
    "She bought a new dress for the party.",
    "He painted a beautiful picture.",
    "They watched a thrilling movie.",
    "The students completed their homework.",
    "I cleaned the house thoroughly.",
    "We went shopping for groceries.",
    "She sang her favorite song.",
    "He played video games with his brother.",
    "The rain stopped suddenly.",
    "I practiced playing the piano.",
    "They went for a jog in the park.",
    "She helped her neighbor with gardening.",
    "He fixed the leaky faucet.",
    "We celebrated a friend's birthday.",
    "The cat chased a butterfly.",
    "I wrote a poem last week.",
    "She baked a delicious cake.",
    "He walked the dog in the evening.",
    "They watched fireworks on New Year's Eve.",
    "I enjoyed a cup of coffee in the morning.",
    "We visited the beach during the holidays.",
    "She went skiing in the mountains.",
    "He took a photograph of the sunset.",
    "They had a barbecue in the backyard.",
    "She practiced yoga in the park.",
    "He fixed his bicycle tire.",
    "They attended a concert downtown.",
    "The baby crawled for the first time.",
    "I cooked spaghetti for dinner.",
    "We volunteered at the local shelter.",
    "She finished knitting a scarf.",
    "He played soccer with his friends.",
    "They went on a road trip to the mountains.",
    "The teacher explained the math problem.",
    "I watched a documentary about space.",
    "We went swimming at the pool.",
    "She learned how to bake bread.",
    "He planted vegetables in the garden.",
    "They had a picnic in the backyard.",
    "The cat slept on the windowsill.",
    "I wrote a thank-you note.",
    "We rode bicycles in the park.",
    "She visited the art museum.",
    "He painted the walls of his room.",
    "They explored a new hiking trail.",
    "The rainbows appeared after the rain.",
    "I played the guitar at the talent show.",
    "We assembled a puzzle together.",
    "She organized her bookshelf.",
    "He ran a marathon last month.",
    "They built a sandcastle at the beach.",
    "The dog fetched a stick.",
    "I read a bedtime story to my niece.",
    "We had a barbecue in the park.",
    "She sketched a beautiful landscape.",
    "He solved a difficult puzzle.",
    "They went ice skating at the rink.",
    "The bird chirped outside the window.",
    "I helped my friend move houses.",
    "We painted Easter eggs.",
    "She rode a horse at the ranch.",
    "He collected seashells on the shore.",
    "They hiked to the top of the hill.",
    "She made a delicious sandwich for lunch.",
    "He fixed the broken chair.",
    "They explored the ancient ruins.",
    "The baby smiled at everyone.",
    "I wrote a story about dragons.",
    "We planted flowers in the garden.",
    "She danced in the rain.",
    "He played the piano beautifully.",
    "They visited a zoo and saw lions.",
    "The teacher explained the history lesson.",
    "I watched a comedy movie with friends.",
    "We baked cookies for a charity event.",
    "She practiced basketball in the backyard.",
    "He cleaned his car inside and out.",
    "They went on a nature hike.",
    "The cat chased a butterfly around the yard.",
    "I drew a picture of my family.",
    "We volunteered at a homeless shelter.",
    "She learned how to sew a dress.",
    "He built a birdhouse for the garden.",
    "They had a picnic in the countryside.",
    "The sun set behind the mountains.",
    "I played chess with my grandfather.",
    "We went snorkeling at the beach.",
    "She read a mystery novel in one sitting.",
    "He organized a charity fundraiser.",
    "They attended a music festival.",
    "The dog fetched a ball from the lake.",
    "I practiced meditation in the morning.",
    "We painted a mural on the wall.",
    "She assembled a model airplane.",
    "He fixed a leaky faucet in the kitchen.",
    "They went horseback riding in the forest.",
    "The flowers bloomed in the spring.",
    "I wrote a letter to my future self.",
    "We visited a science museum.",
    "She planted a tree in the backyard.",
    "He cooked a traditional dish from his country.",
    "They went camping in the wilderness.",
    "The baby giggled at a funny noise.",
    "I learned how to juggle three balls.",
    "We took a train ride through the countryside.",
    "She swam in the pool for hours.",
    "He played fetch with his dog.",
    "They attended a dance performance.",
    "The cat napped in the sun.",
    "I made a handmade birthday card.",
    "We visited an amusement park.",
    "She hiked up a steep mountain trail.",
    "He fixed the flat tire on his bike.",
    "They explored the hidden caves.",
    "The baby took its first steps.",
    "I wrote a poem about nature.",
    "We planted vegetables in raised beds.",
    "She sang a lullaby to her baby brother.",
    "He played soccer in the neighborhood park.",
    "They visited a famous landmark.",
    "The teacher explained the scientific experiment.",
    "I watched a documentary about wildlife.",
    "We baked a cake for a friend's birthday.",
    "She practiced playing the violin.",
    "He cleaned the entire house.",
    "They went on a bike ride along the river.",
    "The cat chased a laser pointer.",
    "I painted a landscape on canvas.",
    "We volunteered at an animal shelter.",
    "She learned how to knit a scarf.",
    "He built a wooden bird feeder.",
    "They had a barbecue in the backyard.",
    "The sun rose over the horizon.",
    "I played board games with my family.",
    "We went kayaking on the lake.",
    "She read a fantasy novel under a tree.",
    "He organized a charity marathon.",
    "They attended a cultural festival.",
    "The dog fetched a frisbee at the park.",
    "I practiced yoga in the garden.",
    "We painted a mural on the school wall.",
    "She assembled a model ship.",
    "He fixed a leaky roof.",
    "They went horse riding on a ranch.",
    "The flowers blossomed in vibrant colors.",
    "I wrote a diary entry about my day.",
    "We visited an art gallery downtown.",
    "She planted a garden full of flowers.",
    "He cooked a traditional meal from scratch.",
    "They went backpacking in the mountains.",
    "The baby babbled happily.",
    "I learned how to play a new musical instrument.",
    "We took a ferry ride to an island.",
    "She swam laps in the pool.",
    "He played fetch with his dog at the beach.",
    "They attended a theatrical performance.",
    "The cat purred contentedly.",
    "I created handmade jewelry.",
    "We went on a roller coaster at the theme park.",
    "She hiked through a dense forest.",
    "He fixed a broken toy.",
    "They explored a historic castle.",
    "The baby cuddled with a stuffed animal.",
    "I wrote a short story about friendship.",
    "We built a sandcastle on the beach.",
    "She took care of plants in the greenhouse.",
    "He cooked dinner for his family.",
    "They went on a hot air balloon ride.",
    "The dog wagged its tail happily.",
    "I practiced martial arts in the dojo.",
    "We painted a mural in the community center.",
    "She hopped across the stepping stones.",
    "He fixed the broken fence in the yard.",
    "They explored the winding forest trails.",
    "The baby laughed at the funny faces.",
    "I wrote a letter to my future self.",
    "We planted rows of sunflowers in the garden.",
    "She sang a melody that echoed through the room.",
    "He played basketball with great enthusiasm.",
    "They visited an ancient archaeological site.",
    "The teacher explained the complex scientific theory.",
    "I watched a documentary about ocean creatures.",
    "We baked cupcakes for a school fundraiser.",
    "She practiced playing the flute diligently.",
    "He cleaned the cluttered garage thoroughly.",
    "They went on a nature walk along the creek.",
    "The cat pounced on a toy mouse playfully.",
    "I painted a portrait of a serene landscape.",
    "We volunteered at a local soup kitchen.",
    "She learned how to crochet a blanket.",
    "He built a small wooden birdhouse for the garden.",
    "They had a picnic in a picturesque meadow.",
    "The sun peeked through the clouds.",
    "I played chess against a formidable opponent.",
    "We went snorkeling to explore underwater life.",
    "She read a thrilling mystery novel late into the night.",
    "He organized a fundraising event for charity.",
    "They attended a lively music concert.",
    "The dog eagerly fetched a ball in the park.",
    "I practiced mindfulness meditation daily.",
    "We painted vibrant murals in the community.",
    "She assembled intricate origami sculptures.",
    "He repaired a faulty electrical circuit.",
    "They went horseback riding through scenic trails.",
    "The flowers exuded a fragrant aroma.",
    "I documented my thoughts in a journal.",
    "We visited an interactive science museum.",
    "She cultivated a variety of herbs in the garden.",
    "He cooked a sumptuous feast for a celebration.",
    "They embarked on a thrilling backpacking adventure.",
    "The baby clapped its hands in delight.",
    "I mastered a new musical composition.",
    "We took a ferry trip to explore nearby islands.",
    "She swam laps vigorously at the pool.",
    "He played fetch with his dog in the river.",
    "They attended a captivating theater performance.",
    "The cat lounged lazily in the sunshine.",
    "I crafted intricate sculptures from clay.",
    "We rode exhilarating roller coasters at the amusement park.",
    "She trekked through challenging mountain terrain.",
    "He repaired a malfunctioning gadget.",
    "They explored the mysterious underground caves.",
    "The baby cooed and giggled joyfully.",
    "I penned a captivating short story.",
    "We constructed elaborate sand sculptures on the beach.",
    "She tended to a variety of exotic plants.",
    "He prepared a delicious breakfast for the family.",
    "They soared high on a hot air balloon adventure.",
    "The dog bounded happily through the fields.",
    "I honed my skills in martial arts practice.",
    "We adorned the walls with colorful community murals.",
    "She skipped along the cobblestone path.",
    "He repaired the squeaky door hinges.",
    "They explored the vast, open plains.",
    "The baby gurgled and smiled brightly.",
    "I wrote a poem about the changing seasons.",
    "We planted a diverse array of vegetables.",
    "She sang a beautiful melody that resonated deeply.",
    "He played football with incredible skill.",
    "They visited a renowned historical monument.",
    "The teacher elucidated the intricate mathematical concept.",
    "I watched a fascinating documentary on space exploration.",
    "We baked batches of cookies for a charity bake sale.",
    "She practiced the piano diligently every day.",
    "He cleaned the attic, organizing it meticulously.",
    "They went on a scenic hike amidst lush greenery.",
    "The cat leaped after a fluttering butterfly.",
    "I painted a vivid sunset over the ocean.",
    "We volunteered at a shelter for homeless animals.",
    "She mastered the art of knitting intricate patterns.",
    "He constructed a sturdy wooden bookshelf.",
    "They enjoyed a cozy picnic in a serene meadow.",
    "The sun illuminated the sky with vibrant hues.",
    "I played a challenging game of strategic chess.",
    "We explored the mesmerizing coral reefs while snorkeling.",
    "She read an enthralling mystery novel under the stars.",
    "He organized a successful fundraiser for a noble cause.",
    "They attended a dynamic music festival in the city.",
    "The dog eagerly fetched a frisbee at the beach.",
    "I practiced calming meditation techniques.",
    "We adorned the walls with captivating street art.",
    "She crafted delicate paper origami figures.",
    "He repaired a malfunctioning household appliance.",
    "They galloped through picturesque countryside on horseback.",
    "The flowers emitted a delightful fragrance.",
    "I chronicled my daily experiences in a journal.",
    "We visited an interactive children's museum.",
    "She nurtured a thriving herb garden.",
    "He prepared a delectable feast for a special occasion.",
    "They embarked on an exhilarating mountain-climbing expedition.",
    "The baby giggled and clapped in pure delight.",
    "I composed an intricate musical symphony.",
    "We embarked on an adventurous boat excursion to islands.",
    "She swam laps with remarkable speed at the pool.",
    "He played fetch with his dog in a scenic park.",
    "They savored a mesmerizing theatrical performance.",
    "The cat lounged leisurely in the cozy sunbeam.",
    "I sculpted intricate figurines from fine clay.",
    "We enjoyed thrilling rides at the amusement park.",
    "She trekked through challenging terrains of the mountains.",
    "He fixed a malfunctioning electronic device.",
    "They explored the mysterious depths of underground caverns.",
    "The baby cooed and laughed in sheer happiness.",
    "I penned an engaging and compelling short story.",
    "We constructed elaborate sandcastles on the sandy shore.",
    "She cared for a variety of vibrant, exotic plants.",
    "He prepared a scrumptious brunch for the family.",
    "They floated high above in a majestic hot air balloon.",
    "The dog frolicked playfully in the open fields.",
    "I practiced and honed my martial arts techniques.",
    "We adorned the community walls with vibrant murals.",
    "She strolled leisurely along the scenic riverside.",
    "He fixed the wobbly table leg with precision.",
    "They explored the dense and enchanting forests.",
    "The baby babbled happily, amused by a toy.",
    "I wrote a story about a magical adventure.",
    "We planted a variety of colorful flowers in the garden.",
    "She sang a captivating song that resonated deeply.",
    "He played basketball with incredible finesse.",
    "They visited an awe-inspiring natural wonder.",
    "The teacher explained a complex scientific theory concisely.",
    "I watched an intriguing documentary on ancient civilizations.",
    "We baked scrumptious muffins for a school fundraiser.",
    "She diligently practiced playing the guitar.",
    "He meticulously organized the cluttered garage.",
    "They embarked on an exhilarating mountain-climbing expedition.",
    "The cat stealthily pounced on a passing shadow.",
    "I painted a vibrant rainbow stretching across the sky.",
    "We volunteered at a shelter for abandoned pets.",
    "She mastered the art of creating intricate pottery.",
    "He crafted a beautiful wooden chest for storage.",
    "They enjoyed a delightful picnic in a blooming orchard.",
    "The sun radiated warmth and painted the sky golden.",
    "I engaged in a competitive chess match with a friend.",
    "We explored the breathtaking coral reefs while snorkeling.",
    "She immersed herself in a thrilling mystery novel.",
    "He organized a successful charity event for a good cause.",
    "They attended a lively and vibrant music festival.",
    "The dog joyfully chased a flying disc at the park.",
    "I practiced mindfulness and meditation techniques.",
    "We adorned the city walls with stunning graffiti art.",
    "She meticulously crafted delicate origami sculptures.",
    "He repaired a malfunctioning electronic gadget at home.",
    "They trotted on horseback through picturesque landscapes.",
    "The flowers emitted a sweet and soothing fragrance.",
    "I chronicled my thoughts and experiences in a personal diary.",
    "We visited an interactive and educational science museum.",
    "She nurtured a thriving garden of aromatic herbs.",
    "He prepared a delectable feast for a festive celebration.",
    "They embarked on an adventurous backpacking journey.",
    "The baby giggled and clapped in sheer delight.",
    "I composed a melodious and intricate musical composition.",
    "We voyaged on an exciting boat trip to nearby islands.",
    "She swam laps effortlessly at the sparkling pool.",
    "He engaged in a spirited game of fetch with his dog.",
    "They enjoyed an enthralling theatrical performance.",
    "The cat lazily sprawled in a pool of sunlight.",
    "I crafted intricate and detailed sculptures from clay.",
    "We relished exhilarating rides at the bustling amusement park.",
    "She trekked through challenging mountainous terrains.",
    "He repaired a malfunctioning household appliance with expertise.",
    "They ventured deep into the mysterious underground caves.",
    "The baby squealed and laughed with pure joy.",
    "I authored an engaging and thought-provoking short story.",
    "We constructed elaborate and intricate sand sculptures.",
    "She tended to a variety of lush and colorful plants.",
    "He prepared a lavish and sumptuous dinner for the family.",
    "They soared high above in a majestic hot air balloon ride.",
    "The dog frolicked playfully in the expansive fields.",
    "I practiced martial arts diligently to perfect my moves.",
    "We decorated the community walls with captivating murals.",
    "She admired the breathtaking sunset over the horizon.",
    "He fixed the squeaky door hinges with precision.",
    "They explored the charming and quaint village.",
    "The baby clapped and gurgled with innocent delight.",
    "I penned a heartfelt and emotional poem.",
    "We cultivated a delightful array of aromatic herbs.",
    "She sang a melodious tune that echoed in the air.",
    "He played soccer with remarkable agility.",
    "They visited an ancient and historic fortress.",
    "The teacher explained the scientific principles with clarity.",
    "I watched an intriguing documentary on wildlife conservation.",
    "We baked batches of cookies for a fundraising event.",
    "She practiced playing the violin with dedication.",
    "He meticulously cleaned the cluttered attic.",
    "They embarked on a refreshing hike through lush forests.",
    "The cat stealthily stalked a fluttering butterfly.",
    "I painted a serene landscape with vivid colors.",
    "We volunteered at a local animal shelter.",
    "She mastered the art of creating intricate sculptures.",
    "He crafted a sturdy wooden bench for the garden.",
    "They enjoyed a cozy picnic under a shady tree.",
    "The sun cast a golden glow as it descended.",
    "I engaged in a strategic game of chess with a friend.",
    "We explored the vibrant marine life while snorkeling.",
    "She immersed herself in a captivating novel.",
    "He organized a successful charity fundraiser.",
    "They attended an energetic and lively music concert.",
    "The dog gleefully chased after a frisbee at the park.",
    "I practiced calming meditation techniques.",
    "We adorned the city walls with striking street art.",
    "She leisurely walked along the sandy beach.",
    "He fixed the leaky faucet in the kitchen.",
    "They explored the ancient ruins of a lost city.",
    "The baby giggled and crawled across the floor.",
    "I wrote a captivating story about a magical journey.",
    "We planted a variety of fruits in the backyard.",
    "She sang a beautiful melody that echoed in the hall.",
    "He played football with incredible energy.",
    "They visited a renowned historical site.",
    "The teacher explained complex ideas in a simple manner.",
    "I watched an intriguing documentary on wildlife behavior.",
    "We baked delicious cookies for a school fundraiser.",
    "She practiced playing the piano passionately.",
    "He meticulously organized the cluttered closet.",
    "They went on a thrilling mountain-climbing expedition.",
    "The cat stealthily stalked a fluttering butterfly.",
    "I painted a breathtaking sunset over the horizon.",
    "We volunteered at an animal rescue shelter.",
    "She mastered the art of creating intricate pottery.",
    "He crafted a beautiful wooden chair for the porch.",
    "They enjoyed a peaceful picnic in a blooming garden.",
    "The sun illuminated the sky with a radiant glow.",
    "I engaged in an intense game of chess with a friend.",
    "We explored mesmerizing coral reefs while snorkeling.",
    "She read an enthralling mystery novel late into the night.",
    "He organized a successful charity event for a noble cause.",
    "They attended a lively and vibrant music festival.",
    "The dog eagerly chased a frisbee in the park.",
    "I practiced calming meditation techniques.",
    "We adorned the city walls with stunning graffiti art.",
    "She meticulously crafted delicate origami sculptures.",
    "He repaired a malfunctioning electronic gadget at home.",
    "They trotted on horseback through picturesque landscapes.",
    "The flowers emitted a sweet and soothing fragrance.",
    "I chronicled my thoughts and experiences in a personal diary.",
    "We visited an interactive and educational science museum.",
    "She nurtured a thriving garden of aromatic herbs.",
    "He prepared a delectable feast for a festive celebration.",
    "They embarked on an adventurous backpacking journey.",
    "The baby giggled and clapped in sheer delight.",
    "I composed a melodious and intricate musical composition.",
    "We voyaged on an exciting boat trip to nearby islands.",
    "She swam laps effortlessly at the sparkling pool.",
    "He engaged in a spirited game of fetch with his dog.",
    "They enjoyed an enthralling theatrical performance.",
    "The cat lazily sprawled in a pool of sunlight.",
    "I crafted intricate and detailed sculptures from clay.",
    "We relished exhilarating rides at the bustling amusement park.",
    "She trekked through challenging mountainous terrains.",
    "He repaired a malfunctioning household appliance with expertise.",
    "They ventured deep into the mysterious underground caves.",
    "The baby cooed and laughed in sheer happiness.",
    "I authored an engaging and thought-provoking short story.",
    "We constructed elaborate and intricate sand sculptures.",
    "She tended to a variety of lush and colorful plants.",
    "He prepared a lavish and sumptuous dinner for the family.",
    "They soared high above in a majestic hot air balloon ride.",
    "The dog frolicked playfully in the expansive fields.",
    "I practiced martial arts diligently to perfect my moves.",
    "We adorned the community walls with captivating murals.",
    "She admired the breathtaking sunset over the horizon.",
    "He fixed the squeaky door hinges with precision.",
    "They explored the charming and quaint village.",
    "The baby clapped and gurgled with innocent delight.",
    "I penned a heartfelt and emotional poem.",
    "We cultivated a delightful array of aromatic herbs.",
    "She sang a melodious tune that echoed in the air.",
    "He played soccer with remarkable agility.",
    "They visited an ancient and historic fortress.",
    "The teacher explained the scientific principles with clarity.",
    "I watched an intriguing documentary on wildlife conservation.",
    "We baked batches of cookies for a fundraising event.",
    "She practiced playing the violin with dedication.",
    "He meticulously cleaned the cluttered attic.",
    "They embarked on a refreshing hike through lush forests.",
    "The cat stealthily stalked a fluttering butterfly.",
    "I painted a serene landscape with vivid colors.",
    "We volunteered at a local animal shelter.",
    "She mastered the art of creating intricate sculptures.",
    "He crafted a sturdy wooden bench for the garden.",
    "They enjoyed a cozy picnic under a shady tree.",
    "The sun cast a golden glow as it descended.",
    "I engaged in a strategic game of chess with a friend.",
    "We explored the vibrant marine life while snorkeling.",
    "She immersed herself in a captivating novel.",
    "He organized a successful charity fundraiser.",
    "They attended an energetic and lively music concert.",
    "The dog gleefully chased after a frisbee at the park.",
    "I practiced calming meditation techniques.",
    "We adorned the city walls with striking street art."
];   
const letterRegex = /^[a-zA-Z0-9\s.]+$/;
const specialKeys = [
    'Shift', 'Control', 'Alt', 'Meta',
    'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight',
    'Enter', 'Tab', 'Escape', 'Backspace',
    'CapsLock', 'PageUp', 'PageDown',
    'Home', 'End', 'Insert',
    'ContextMenu', 'Delete', 'Pause', 'ScrollLock',
    'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'Unidentified'
];
  
