const words = [
    'apple', 'banana', 'delicious', 'yellow', 'fruit',
    'sweet', 'tropical', 'juicy', 'snack', 'peel',
    'crisp', 'smoothie', 'ripe', 'healthy', 'refreshing',
    'tasty', 'nutritious', 'vitamins', 'fiber', 'orchard',
    'energy', 'potassium', 'citrus', 'flavorful',
    'dessert', 'sliced', 'fresh', 'harvest', 'bunch',
    'seedless', 'exotic', 'baked', 'smooth', 'pulpy',
    'peeled', 'fragrant', 'plantation', 'ripened',
    'yellowish', 'wholesome', 'dried', 'organic', 'juice',
    'skin', 'blended', 'ripening', 'clusters', 'fragrance',
    'nectarine', 'citron', 'mango', 'papaya', 'pineapple',
    'citrusy', 'zesty', 'tangy', 'nectar', 'succulent',
    'tart', 'pomegranate', 'kiwi', 'cranberry', 'grapefruit',
    'melon', 'watermelon', 'cantaloupe', 'honeydew', 'plum',
    'peach', 'apricot', 'nectarines', 'fig', 'dates',
    'raisins', 'blueberries', 'strawberries', 'blackberries', 'raspberries',
    'mulberry', 'guava', 'lychee', 'passionfruit', 'dragonfruit',
    'starfruit', 'persimmon', 'quince', 'boysenberry', 'elderberry',
    'gooseberry', 'soursop', 'tamarind', 'cherimoya', 'jackfruit',
    'breadfruit', 'custardapple', 'soursweet', 'luscious', 'exquisite',
    'tempting', 'lively', 'bittersweet', 'sapid', 'palatable',
    'ambrosial', 'delectable', 'ambrosia', 'scrumptious', 'palate',
    'gastronomic', 'mouthwatering', 'yummy', 'toothsome', 'fleshy',
    'succulence', 'tanginess', 'essence', 'bouquet', 'perfumed',
    'aromatic', 'odor', 'fragrancy', 'perfume', 'whiff', 'smell',
    'odorous', 'nutrition', 'orchards', 'vibrant', 'citronella',
    'freshness', 'sensational', 'delicacy', 'melange', 'exoticism',
    'orchestration', 'pulchritudinous', 'sumptuous', 'fruitful', 'orchestral',
    'vivid', 'medley', 'tasteful', 'enchanting', 'orchid',
    'divine', 'savor', 'cornucopia', 'enticing', 'savory',
    'variety', 'appetizing', 'alluring', 'enticement', 'olfactory',
    'delectation', 'lusciousness', 'temptation', 'odorant', 'intoxicating',
    'olfaction', 'enjoyable', 'fragrantly', 'appetence', 'fragranced',
    'taste', 'fragrantly', 'scent', 'fragrantly',    
];    
const letterRegex = /^[a-zA-Z]$/;